### ISSUE TITLE
eventually-postgres: crate documentation in eventually

### ISSUE THREAD

**Issue by ar3s3ru** [ar3s3ru/eventually-rs#117]
The [documentation for `eventually-postgres`](https://ar3s3ru.github.io/eventually-rs/eventually_postgres/index.html) is not visible in the public crate documentation.

As a result, users interested in using the Postgres `EventStore` implementation don't know how to.

From #116

**Comment by pseudo-su** [comment]
Just a thought, but I'd find it really useful to have a version of the example app that was easy to get running locally w/ a postgres event store. Going through the current docs I can't quite grok if/how a "real" app would need to think about things like schema migrations etc.

I think Ideally you'd be able to just `docker-compose up` the example app and then poke around in the postgres DB.

Something along these lines:

```ini
# .env
POSTGRES_USER=user
POSTGRES_PASSWORD=password
POSTGRES_DB=eventually-app-example-db
```

```yaml
# docker-compose.yml
version: '3'
services:
  example_db:
    container_name: "example-db"
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  example_app:
    container_name: "example-app"
    depends_on:
      - example_db
    ports:
      - "8080:8080"
    env_file:
      - .env
    
volumes:
  database-data:
```
